In [227]:
import pandas as pd
import os

desktop_path = os.path.join(os.path.expanduser('~'), 'Desktop')
sheet_filename = 'M-X_CIFs_full_occupancy_sorted_tags_element_pairs.xlsx'
sheet_path = os.path.join(desktop_path, sheet_filename)

# Read the Excel file
xl = pd.ExcelFile(sheet_path)

# Initialize an empty list to store DataFrames for each sheet
dfs = []

# Iterate over each sheet, read data, and append sheet name as a new column
for sheet_name in xl.sheet_names:
    df = xl.parse(sheet_name)  # Read data from the current sheet
    df['Compound'] = sheet_name  # Add a new column with sheet name
    dfs.append(df)  # Append the modified DataFrame to the list

# Concatenate all DataFrames into a single DataFrame
result_df = pd.concat(dfs, ignore_index=True)

# Filtering the DataFrame
# Define lists of M and X elements
M_elements = ['Fe', 'Co', 'Ni', 'Ru', 'Rh', 'Pd', 'Os', 'Ir', 'Pt']
X_elements = ['Si', 'Ga', 'Ge', 'In', 'Sn', 'Sb']

# Filter the DataFrame based on M and X elements
MX = result_df[result_df['Compound'].apply(lambda x: any(m in x for m in M_elements)) & 
                        result_df['Compound'].apply(lambda x: any(x.endswith('-' + x_elem) for x_elem in X_elements))]

# Selecting desired columns
desired_columns = ['File', 'Distance', 'Atomic Mixing', 'Compound']
MX = MX[desired_columns]

# Group by M and X elements and calculate average and standard deviation of Distance
grouped_MX = MX.groupby('Compound').agg({'Distance': ['mean', 'std']})

# Flatten MultiIndex columns
grouped_MX.columns = ['_'.join(col).strip() for col in grouped_MX.columns.values]

# Reset index
grouped_MX.reset_index(inplace=True)

# Save grouped_df as Excel
excel_filename = 'MX_grouped_data.xlsx'
excel_path = os.path.join(desktop_path, excel_filename)

grouped_MX.to_excel(excel_path, index=False)
print(f"Data has been saved to '{excel_path}'")

Data has been saved to '/Users/emiljaffal/Desktop/MX_grouped_data.xlsx'

In [228]:
sheet_filename = 'R-X_CIFs_full_occupancy_sorted_tags_element_pairs.xlsx'
sheet_path = os.path.join(desktop_path, sheet_filename)

# Read the Excel file
xl = pd.ExcelFile(sheet_path)

# Initialize an empty list to store DataFrames for each sheet
dfs = []

# Iterate over each sheet, read data, and append sheet name as a new column
for sheet_name in xl.sheet_names:
    df = xl.parse(sheet_name)  # Read data from the current sheet
    df['Compound'] = sheet_name  # Add a new column with sheet name
    dfs.append(df)  # Append the modified DataFrame to the list

# Concatenate all DataFrames into a single DataFrame
result_df = pd.concat(dfs, ignore_index=True)

# Filtering the DataFrame
# Define lists of M and X elements
R_elements = ['Sc', 'Y', 'La', 'Ce', 'Pr', 'Nd', 'Sm', 'Eu', 'Gd', 'Tb', 'Dy', 'Ho', 'Er', 'Tm', 'Yb', 'Lu', 'Th', 'U']
X_elements = ['Si', 'Ga', 'Ge', 'In', 'Sn', 'Sb']

# Filter the DataFrame based on M and X elements
RX = result_df[result_df['Compound'].apply(lambda x: any(r in x for r in R_elements)) & 
                        result_df['Compound'].apply(lambda x: any(x.endswith('-' + x_elem) for x_elem in X_elements))]

# Selecting desired columns
desired_columns = ['File', 'Distance', 'Atomic Mixing', 'Compound']
RX = RX[desired_columns]

# Group by M and X elements and calculate average and standard deviation of Distance
grouped_RX = RX.groupby('Compound').agg({'Distance': ['mean', 'std']})

# Flatten MultiIndex columns
grouped_RX.columns = ['_'.join(col).strip() for col in grouped_RX.columns.values]

# Reset index
grouped_RX.reset_index(inplace=True)

# Save grouped_df as Excel
excel_filename = 'RX_grouped_data.xlsx'
excel_path = os.path.join(desktop_path, excel_filename)

grouped_RX.to_excel(excel_path, index=False)
print(f"Data has been saved to '{excel_path}'")

Data has been saved to '/Users/emiljaffal/Desktop/RX_grouped_data.xlsx'

In [229]:
sheet_filename = 'R-M_CIFs_full_occupancy_sorted_tags_element_pairs.xlsx'
sheet_path = os.path.join(desktop_path, sheet_filename)

# Read the Excel file
xl = pd.ExcelFile(sheet_path)

# Initialize an empty list to store DataFrames for each sheet
dfs = []

# Iterate over each sheet, read data, and append sheet name as a new column
for sheet_name in xl.sheet_names:
    df = xl.parse(sheet_name)  # Read data from the current sheet
    df['Compound'] = sheet_name  # Add a new column with sheet name
    dfs.append(df)  # Append the modified DataFrame to the list

# Concatenate all DataFrames into a single DataFrame
result_df = pd.concat(dfs, ignore_index=True)

# Filtering the DataFrame
# Define lists of M and X elements
R_elements = ['Sc', 'Y', 'La', 'Ce', 'Pr', 'Nd', 'Sm', 'Eu', 'Gd', 'Tb', 'Dy', 'Ho', 'Er', 'Tm', 'Yb', 'Lu', 'Th', 'U']
M_elements = ['Fe', 'Co', 'Ni', 'Ru', 'Rh', 'Pd', 'Os', 'Ir', 'Pt']

# Filter the DataFrame based on M and X elements
RM = result_df[result_df['Compound'].apply(lambda x: any(r in x for r in R_elements)) & 
                        result_df['Compound'].apply(lambda x: any(x.endswith('-' + m_elem) for m_elem in M_elements))]

# Selecting desired columns
desired_columns = ['File', 'Distance', 'Atomic Mixing', 'Compound']
RM = RM[desired_columns]

# Group by M and X elements and calculate average and standard deviation of Distance
grouped_RM = RM.groupby('Compound').agg({'Distance': ['mean', 'std']})

# Flatten MultiIndex columns
grouped_RM.columns = ['_'.join(col).strip() for col in grouped_RM.columns.values]

# Reset index
grouped_RM.reset_index(inplace=True)

# Save grouped_df as Excel
excel_filename = 'RM_grouped_data.xlsx'
excel_path = os.path.join(desktop_path, excel_filename)

grouped_RM.to_excel(excel_path, index=False)

print(f"Data has been saved to '{excel_path}'")

Data has been saved to '/Users/emiljaffal/Desktop/RM_grouped_data.xlsx'

In [230]:
sheet_filename = 'R-M-X_full_occupancy_element_pairs.xlsx'
sheet_path = os.path.join(desktop_path, sheet_filename)

# Read the Excel file
xl = pd.ExcelFile(sheet_path)

# Initialize an empty list to store DataFrames for each sheet
dfs = []

# Iterate over each sheet, read data, and append sheet name as a new column
for sheet_name in xl.sheet_names:
    df = xl.parse(sheet_name)  # Read data from the current sheet
    df['Compound'] = sheet_name  # Add a new column with sheet name
    dfs.append(df)  # Append the modified DataFrame to the list

# Concatenate all DataFrames into a single DataFrame
result_df = pd.concat(dfs, ignore_index=True)

# Filtering the DataFrame
# Define lists of M and X elements
R_elements = ['Sc', 'Y', 'La', 'Ce', 'Pr', 'Nd', 'Sm', 'Eu', 'Gd', 'Tb', 'Dy', 'Ho', 'Er', 'Tm', 'Yb', 'Lu', 'Th', 'U']
M_elements = ['Fe', 'Co', 'Ni', 'Ru', 'Rh', 'Pd', 'Os', 'Ir', 'Pt']
X_elements = ['Si', 'Ga', 'Ge', 'In', 'Sn', 'Sb']

# Filtering the DataFrame for R-M, R-X, and M-X compounds
RMX = result_df[
    # R-M compounds
    result_df['Compound'].apply(lambda x: any(r in x for r in R_elements)) &
    result_df['Compound'].apply(lambda x: any(x.endswith('-' + m_elem) for m_elem in M_elements)) |
    # R-X compounds
    result_df['Compound'].apply(lambda x: any(r in x for r in R_elements)) &
    result_df['Compound'].apply(lambda x: any(x.endswith('-' + x_elem) for x_elem in X_elements)) |
    # M-X compounds
    result_df['Compound'].apply(lambda x: any(m_elem + '-' + x_elem in x for m_elem in M_elements for x_elem in X_elements))]

# Selecting desired columns
desired_columns = ['File', 'Distance', 'Atomic Mixing', 'Compound']
RMX = RMX[desired_columns]

# Group by M and X elements and calculate average and standard deviation of Distance
grouped_RMX = RMX.groupby('Compound').agg({'Distance': ['mean', 'std']})

# Flatten MultiIndex columns
grouped_RMX.columns = ['_'.join(col).strip() for col in grouped_RMX.columns.values]

# Reset index
grouped_RMX.reset_index(inplace=True)

# Save grouped_df as Excel
excel_filename = 'RMX_grouped_data.xlsx'
excel_path = os.path.join(desktop_path, excel_filename)

grouped_RMX.to_excel(excel_path, index=False)

print(f"Data has been saved to '{excel_path}'")

Data has been saved to '/Users/emiljaffal/Desktop/RMX_grouped_data.xlsx'

In [231]:
# Concatenate along rows
RM_RX_MX = pd.concat([RM, RX, MX], axis=0)

# Reset index if needed
RM_RX_MX.reset_index(drop=True, inplace=True)
RM_RX_MX['binary'] = 'Yes'
RMX['binary'] = 'No'

In [232]:
All = pd.concat([RMX, RM_RX_MX], axis=0)
All.drop(columns=['File', 'Atomic Mixing'], inplace=True)

In [233]:
# Convert 'Distance' column to numeric
All['Distance'] = pd.to_numeric(All['Distance'])

# Group by 'Compound' column
grouped = All.groupby('Compound')

# Define a function to calculate average and standard deviation based on 'binary' values
def calculate_stats(group):
    if all(group['binary'] == 'No'):
        return pd.Series([group['Distance'].mean(), group['Distance'].std(), None, None],
                         index=['Ternary Average', 'Ternary SD', 'Binary Average', 'Binary SD'])
    elif all(group['binary'] == 'Yes'):
        return pd.Series([None, None, group['Distance'].mean(), group['Distance'].std()],
                         index=['Ternary Average', 'Ternary SD', 'Binary Average', 'Binary SD'])
    else:
        # If there are mixed values, calculate both
        ternary_mean = group[group['binary'] == 'No']['Distance'].mean()
        ternary_std = group[group['binary'] == 'No']['Distance'].std()
        binary_mean = group[group['binary'] == 'Yes']['Distance'].mean()
        binary_std = group[group['binary'] == 'Yes']['Distance'].std()
        return pd.Series([ternary_mean, ternary_std, binary_mean, binary_std],
                         index=['Ternary Average', 'Ternary SD', 'Binary Average', 'Binary SD'])

# Apply the function to each group and concatenate the results
result = grouped.apply(calculate_stats).reset_index()
result

    Compound  Ternary Average  Ternary SD  Binary Average  Binary SD
0      Ce-Co         2.945909    0.256769        2.861275   0.095718
1      Ce-Fe         2.990000    0.349311        2.958659   0.094747
2      Ce-Ga         3.124191    0.106562        3.232139   0.206619
3      Ce-Ge         3.106902    0.105346        3.080789   0.070186
4      Ce-In         3.253179    0.077243        3.331054   0.105932
..       ...              ...         ...             ...        ...
315    Yb-Rh         2.924235    0.090897        3.020333   0.105078
316    Yb-Ru         3.051000         NaN        3.012667   0.088912
317    Yb-Sb         3.409333    0.302004        3.100437   0.087761
318    Yb-Si         2.943827    0.142639        2.842700   0.099316
319    Yb-Sn         3.125818    0.245378        3.211941   0.130100

[320 rows x 5 columns]

In [234]:
# Rename 'File' column to 'Entry' after removing '.cif' suffix
MX['Entry'] = MX['File'].str.replace('.cif', '')
MX = MX.drop(columns=['File'])

desktop_path = os.path.join(os.path.expanduser('~'), 'Desktop')
sheet_filename = 'binary_M-X.xlsx'
sheet_path = os.path.join(desktop_path, sheet_filename)

# Read the Excel file
MX_2 = pd.read_excel(sheet_path)

# Convert 'Entry' column to the same data type in both DataFrames
MX_2['Entry'] = MX_2['Entry'].astype(str)

# Merge the DataFrames
merged_MX_2 = pd.merge(MX, MX_2[['Entry', 'Formula']], on='Entry', how='left')
merged_MX_2

      Distance   Atomic Mixing Compound    Entry Formula
0        2.386  full_occupancy    Ni-Sn  1250691    NiSn
1        2.444  full_occupancy    Ni-Sn   554689  Ni3Sn2
2        2.450  full_occupancy    Ni-Sn  1837984  Ni3Sn2
3        2.450  full_occupancy    Ni-Sn  1819720  Ni3Sn2
4        2.452  full_occupancy    Ni-Sn  1002170  Ni3Sn2
...        ...             ...      ...      ...     ...
1280     2.426  full_occupancy    Os-Si   555792   OsSi2
1281     2.439  full_occupancy    Os-Si   452823   OsSi2
1282     2.457  full_occupancy    Os-Si   456001    OsSi
1283     2.481  full_occupancy    Os-Ga   261309   Ga3Os
1284     2.481  full_occupancy    Os-Ga   526972   Ga3Os

[1285 rows x 5 columns]

In [235]:
# Rename 'File' column to 'Entry' after removing '.cif' suffix
RX['Entry'] = RX['File'].str.replace('.cif', '')
RX = RX.drop(columns=['File'])

desktop_path = os.path.join(os.path.expanduser('~'), 'Desktop')
sheet_filename = 'binary_R-X.xlsx'
sheet_path = os.path.join(desktop_path, sheet_filename)

# Read the Excel file
RX_2 = pd.read_excel(sheet_path)

# Convert 'Entry' column to the same data type in both DataFrames
RX_2['Entry'] = RX_2['Entry'].astype(str)

# Merge the DataFrames
merged_RX_2 = pd.merge(RX, RX_2[['Entry', 'Formula']], on='Entry', how='left')
merged_RX_2

      Distance   Atomic Mixing Compound    Entry Formula
0        2.888  full_occupancy    Eu-Si   525300    EuSi
1        3.079  full_occupancy    Eu-Si  1810191   Eu2Si
2        3.105  full_occupancy    Eu-Si  2040771   EuSi2
3        3.110  full_occupancy    Eu-Si  1810725   Eu2Si
4        3.126  full_occupancy    Eu-Si   455984   EuSi2
...        ...             ...      ...      ...     ...
2892     3.159  full_occupancy    Th-Sb   453382    SbTh
2893     3.159  full_occupancy    Th-Sb   531000    SbTh
2894     3.182  full_occupancy    Th-Sb   451240   Sb2Th
2895     3.240  full_occupancy    Th-Sb   451241  Sb4Th3
2896     3.248  full_occupancy    Th-Sb   534387  Sb4Th3

[2897 rows x 5 columns]

In [236]:
# Rename 'File' column to 'Entry' after removing '.cif' suffix
RM['Entry'] = RM['File'].str.replace('.cif', '')
RM = RM.drop(columns=['File'])

desktop_path = os.path.join(os.path.expanduser('~'), 'Desktop')
sheet_filename = 'binary_R-M.xlsx'
sheet_path = os.path.join(desktop_path, sheet_filename)

# Read the Excel file
RM_2 = pd.read_excel(sheet_path)

# Convert 'Entry' column to the same data type in both DataFrames
RM_2['Entry'] = RM_2['Entry'].astype(str)

# Merge the DataFrames
merged_RM_2 = pd.merge(RM, RM_2[['Entry', 'Formula']], on='Entry', how='left')
merged_RM_2

      Distance   Atomic Mixing Compound    Entry  Formula
0        2.707  full_occupancy    Nd-Fe  1643161  Fe17Nd5
1        2.856  full_occupancy    Nd-Fe   260460    Fe5Nd
2        2.909  full_occupancy    Nd-Fe  1430804  Fe17Nd5
3        2.968  full_occupancy    Nd-Fe  1721845  Fe17Nd5
4        2.968  full_occupancy    Nd-Fe   554633  Fe17Nd5
...        ...             ...      ...      ...      ...
4436     2.899  full_occupancy    Yb-Rh   458147     RhYb
4437     3.081  full_occupancy    Yb-Rh   458151    Rh2Yb
4438     3.081  full_occupancy    Yb-Rh   526157    Rh2Yb
4439     3.076  full_occupancy    Yb-Os   526180    Os2Yb
4440     3.090  full_occupancy    Yb-Os   458157    Os2Yb

[4441 rows x 5 columns]

In [237]:
merged_binary_new=pd.concat([merged_RM_2,merged_RX_2,merged_MX_2])
merged_binary_new

      Distance   Atomic Mixing Compound    Entry  Formula
0        2.707  full_occupancy    Nd-Fe  1643161  Fe17Nd5
1        2.856  full_occupancy    Nd-Fe   260460    Fe5Nd
2        2.909  full_occupancy    Nd-Fe  1430804  Fe17Nd5
3        2.968  full_occupancy    Nd-Fe  1721845  Fe17Nd5
4        2.968  full_occupancy    Nd-Fe   554633  Fe17Nd5
...        ...             ...      ...      ...      ...
1280     2.426  full_occupancy    Os-Si   555792    OsSi2
1281     2.439  full_occupancy    Os-Si   452823    OsSi2
1282     2.457  full_occupancy    Os-Si   456001     OsSi
1283     2.481  full_occupancy    Os-Ga   261309    Ga3Os
1284     2.481  full_occupancy    Os-Ga   526972    Ga3Os

[8623 rows x 5 columns]

In [238]:
import pandas as pd
import re

# Assuming 'merged_binary_new' is your DataFrame

# Split Compound column into Element 1 and Element 2
merged_binary_new[['Element 1', 'Element 2']] = merged_binary_new['Compound'].str.split('-', expand=True)

# Function to extract element composition
def extract_composition(row, element):
    try:
        # Find the element in the formula
        element_index = row['Formula'].index(row[element])
        # Extract the substring after the element
        composition_str = ''
        for char in row['Formula'][element_index + len(row[element]):]:
            if char.isdigit():
                composition_str += char
            elif char.isalpha():
                break
        composition = int(composition_str)
    except (AttributeError, ValueError, KeyError):
        composition = None
    return composition

# Extract Element 1 Composition
merged_binary_new['Element 1 Composition'] = merged_binary_new.apply(lambda row: extract_composition(row, 'Element 1'), axis=1)

# Extract Element 2 Composition
merged_binary_new['Element 2 Composition'] = merged_binary_new.apply(lambda row: extract_composition(row, 'Element 2'), axis=1)

# Change all NaNs to 1
merged_binary_new['Element 1 Composition'] = merged_binary_new['Element 1 Composition'].fillna(1).astype(int)
merged_binary_new['Element 2 Composition'] = merged_binary_new['Element 2 Composition'].fillna(1).astype(int)

# Calculate Element 1 At. %
merged_binary_new['Element 1 At. %'] = (merged_binary_new['Element 1 Composition'] / (merged_binary_new['Element 1 Composition'] + merged_binary_new['Element 2 Composition'])) * 100

# Calculate Element 2 At. %
merged_binary_new['Element 2 At. %'] = (merged_binary_new['Element 2 Composition'] / (merged_binary_new['Element 1 Composition'] + merged_binary_new['Element 2 Composition'])) * 100

# Round to 2 decimal points
merged_binary_new['Element 1 At. %'] = merged_binary_new['Element 1 At. %'].round(2)
merged_binary_new['Element 2 At. %'] = merged_binary_new['Element 2 At. %'].round(2)

# Reorder columns
merged_binary_new = merged_binary_new[['Distance', 'Atomic Mixing', 'Compound', 'Entry', 'Formula', 'Element 1', 'Element 1 Composition', 'Element 1 At. %', 'Element 2', 'Element 2 Composition', 'Element 2 At. %']]

# Save DataFrame as Excel
excel_filename = 'merged_binary_new.xlsx'
excel_path = os.path.join(desktop_path, excel_filename)

merged_binary_new.to_excel(excel_path, index=False)

print(f"Data has been saved to '{excel_path}'")
merged_binary_new

Data has been saved to '/Users/emiljaffal/Desktop/merged_binary_new.xlsx'

,Distance,Atomic Mixing,Compound,Entry,Formula,Element 1,Element 1 Composition,Element 1 At. %,Element 2,Element 2 Composition,Element 2 At. %
0,2.707,full_occupancy,Nd-Fe,1643161,Fe17Nd5,Nd,5,22.73,Fe,17,77.27
1,2.856,full_occupancy,Nd-Fe,260460,Fe5Nd,Nd,1,16.67,Fe,5,83.33
2,2.909,full_occupancy,Nd-Fe,1430804,Fe17Nd5,Nd,5,22.73,Fe,17,77.27
3,2.968,full_occupancy,Nd-Fe,1721845,Fe17Nd5,Nd,5,22.73,Fe,17,77.27
4,2.968,full_occupancy,Nd-Fe,554633,Fe17Nd5,Nd,5,22.73,Fe,17,77.27
...,...,...,...,...,...,...,...,...,...,...,...
1280,2.426,full_occupancy,Os-Si,555792,OsSi2,Os,1,33.33,Si,2,66.67
1281,2.439,full_occupancy,Os-Si,452823,OsSi2,Os,1,33.33,Si,2,66.67
1282,2.457,full_occupancy,Os-Si,456001,OsSi,Os,1,50.00,Si,1,50.00
1283,2.481,full_occupancy,Os-Ga,261309,Ga3Os,Os,1,25.00,Ga,3,75.00
1284,2.481,full_occupancy,Os-Ga,526972,Ga3Os,Os,1,25.00,Ga,3,75.00

In [239]:
import pandas as pd
import re

# Assuming 'merged_binary_new' is your DataFrame

# Split Compound column into Element 1 and Element 2
merged_binary_new[['Element 1', 'Element 2']] = merged_binary_new['Compound'].str.split('-', expand=True)

# Function to extract element composition
def extract_composition(row, element):
    try:
        # Find the element in the formula
        element_index = row['Formula'].index(row[element])
        # Extract the substring after the element
        composition_str = ''
        for char in row['Formula'][element_index + len(row[element]):]:
            if char.isdigit():
                composition_str += char
            elif char.isalpha():
                break
        composition = int(composition_str)
    except (AttributeError, ValueError, KeyError):
        composition = None
    return composition

# Extract Element 1 Composition
merged_binary_new['Element 1 Composition'] = merged_binary_new.apply(lambda row: extract_composition(row, 'Element 1'), axis=1)

# Extract Element 2 Composition
merged_binary_new['Element 2 Composition'] = merged_binary_new.apply(lambda row: extract_composition(row, 'Element 2'), axis=1)

# Change all NaNs to 1
merged_binary_new['Element 1 Composition'] = merged_binary_new['Element 1 Composition'].fillna(1).astype(int)
merged_binary_new['Element 2 Composition'] = merged_binary_new['Element 2 Composition'].fillna(1).astype(int)

# Calculate Element 1 At. %
merged_binary_new['Element 1 At. %'] = (merged_binary_new['Element 1 Composition'] / (merged_binary_new['Element 1 Composition'] + merged_binary_new['Element 2 Composition'])) * 100

# Calculate Element 2 At. %
merged_binary_new['Element 2 At. %'] = (merged_binary_new['Element 2 Composition'] / (merged_binary_new['Element 1 Composition'] + merged_binary_new['Element 2 Composition'])) * 100

# Round to 2 decimal points
merged_binary_new['Element 1 At. %'] = merged_binary_new['Element 1 At. %'].round(2)
merged_binary_new['Element 2 At. %'] = merged_binary_new['Element 2 At. %'].round(2)

# Reorder columns
merged_binary_new = merged_binary_new[['Distance', 'Atomic Mixing', 'Compound', 'Entry', 'Formula', 'Element 1', 'Element 1 Composition', 'Element 1 At. %', 'Element 2', 'Element 2 Composition', 'Element 2 At. %']]

# Save DataFrame as Excel
excel_filename = 'merged_binary_new.xlsx'
excel_path = os.path.join(desktop_path, excel_filename)

merged_binary_new.to_excel(excel_path, index=False)

print(f"Data has been saved to '{excel_path}'")
merged_binary_new

Data has been saved to '/Users/emiljaffal/Desktop/merged_binary_new.xlsx'

,Distance,Atomic Mixing,Compound,Entry,Formula,Element 1,Element 1 Composition,Element 1 At. %,Element 2,Element 2 Composition,Element 2 At. %
0,2.707,full_occupancy,Nd-Fe,1643161,Fe17Nd5,Nd,5,22.73,Fe,17,77.27
1,2.856,full_occupancy,Nd-Fe,260460,Fe5Nd,Nd,1,16.67,Fe,5,83.33
2,2.909,full_occupancy,Nd-Fe,1430804,Fe17Nd5,Nd,5,22.73,Fe,17,77.27
3,2.968,full_occupancy,Nd-Fe,1721845,Fe17Nd5,Nd,5,22.73,Fe,17,77.27
4,2.968,full_occupancy,Nd-Fe,554633,Fe17Nd5,Nd,5,22.73,Fe,17,77.27
...,...,...,...,...,...,...,...,...,...,...,...
1280,2.426,full_occupancy,Os-Si,555792,OsSi2,Os,1,33.33,Si,2,66.67
1281,2.439,full_occupancy,Os-Si,452823,OsSi2,Os,1,33.33,Si,2,66.67
1282,2.457,full_occupancy,Os-Si,456001,OsSi,Os,1,50.00,Si,1,50.00
1283,2.481,full_occupancy,Os-Ga,261309,Ga3Os,Os,1,25.00,Ga,3,75.00
1284,2.481,full_occupancy,Os-Ga,526972,Ga3Os,Os,1,25.00,Ga,3,75.00

In [240]:
# Rename 'File' column to 'Entry' after removing '.cif' suffix
RMX['Entry'] = RMX['File'].str.replace('.cif', '')
RMX = RMX.drop(columns=['File','binary'])

desktop_path = os.path.join(os.path.expanduser('~'), 'Desktop')
sheet_filename = 'ternary.xlsx'
sheet_path = os.path.join(desktop_path, sheet_filename)

# Read the Excel file
RMX_2 = pd.read_excel(sheet_path)

# Convert 'Entry' column to the same data type in both DataFrames
RMX_2['Entry'] = RMX_2['Entry'].astype(str)

# Merge the DataFrames
merged_RMX_2 = pd.merge(RMX, RMX_2[['Entry', 'Formula']], on='Entry', how='left')
merged_RMX_2

       Distance   Atomic Mixing Compound    Entry     Formula
0         2.032  full_occupancy    Ni-Ge  1008282    Ge3LuNi5
1         2.033  full_occupancy    Ni-Ge  1718687    Ge3Ni5Yb
2         2.034  full_occupancy    Ni-Ge  1402064    ErGe3Ni5
3         2.036  full_occupancy    Ni-Ge  1718681    Ge3Ni5Yb
4         2.036  full_occupancy    Ni-Ge  1818130    Ge3Ni5Tm
...         ...             ...      ...      ...         ...
16298     2.926  full_occupancy    Lu-Os   300201   Ge6Lu4Os7
16299     2.661  full_occupancy    Os-Sn   460299  Os4Sn13Th3
16300     3.377  full_occupancy     U-Sn   461045   Rh4Sn13U3
16301     2.935  full_occupancy     U-Os   538375    Ge6Os7U4
16302     2.880  full_occupancy    Sc-Os   538820   Ge6Os7Sc4

[16303 rows x 5 columns]

In [344]:
merged_RMX_3 = merged_RMX_2.copy()
merged_RMX_3

       Distance   Atomic Mixing Compound    Entry     Formula
0         2.032  full_occupancy    Ni-Ge  1008282    Ge3LuNi5
1         2.033  full_occupancy    Ni-Ge  1718687    Ge3Ni5Yb
2         2.034  full_occupancy    Ni-Ge  1402064    ErGe3Ni5
3         2.036  full_occupancy    Ni-Ge  1718681    Ge3Ni5Yb
4         2.036  full_occupancy    Ni-Ge  1818130    Ge3Ni5Tm
...         ...             ...      ...      ...         ...
16298     2.926  full_occupancy    Lu-Os   300201   Ge6Lu4Os7
16299     2.661  full_occupancy    Os-Sn   460299  Os4Sn13Th3
16300     3.377  full_occupancy     U-Sn   461045   Rh4Sn13U3
16301     2.935  full_occupancy     U-Os   538375    Ge6Os7U4
16302     2.880  full_occupancy    Sc-Os   538820   Ge6Os7Sc4

[16303 rows x 5 columns]

In [345]:
import pandas as pd
import re

# Assuming 'merged_RMX_3' is your DataFrame

# Split Compound column into Element 1 and Element 2
merged_RMX_3[['Element 1', 'Element 2']] = merged_RMX_3['Compound'].str.split('-', expand=True)

# Function to extract element composition
def extract_composition(row, element):
    try:
        # Find the element in the formula
        element_index = row['Formula'].index(row[element])
        # Extract the substring after the element
        composition_str = ''
        for char in row['Formula'][element_index + len(row[element]):]:
            if char.isdigit():
                composition_str += char
            elif char.isalpha():
                break
        composition = int(composition_str)
    except (AttributeError, ValueError, KeyError):
        composition = None
    return composition

# Extract Element 1 Composition
merged_RMX_3['Element 1 Composition'] = merged_RMX_3.apply(lambda row: extract_composition(row, 'Element 1'), axis=1)

# Extract Element 2 Composition
merged_RMX_3['Element 2 Composition'] = merged_RMX_3.apply(lambda row: extract_composition(row, 'Element 2'), axis=1)

# Change all NaNs to 1
merged_RMX_3['Element 1 Composition'] = merged_RMX_3['Element 1 Composition'].fillna(1).astype(int)
merged_RMX_3['Element 2 Composition'] = merged_RMX_3['Element 2 Composition'].fillna(1).astype(int)

# Calculate Element 1 At. %
merged_RMX_3['Element 1 At. %'] = (merged_RMX_3['Element 1 Composition'] / (merged_RMX_3['Element 1 Composition'] + merged_RMX_3['Element 2 Composition'])) * 100

# Calculate Element 2 At. %
merged_RMX_3['Element 2 At. %'] = (merged_RMX_3['Element 2 Composition'] / (merged_RMX_3['Element 1 Composition'] + merged_RMX_3['Element 2 Composition'])) * 100

# Round to 2 decimal points
merged_RMX_3['Element 1 At. %'] = merged_RMX_3['Element 1 At. %'].round(2)
merged_RMX_3['Element 2 At. %'] = merged_RMX_3['Element 2 At. %'].round(2)

# Reorder columns
merged_RMX_3 = merged_RMX_3[['Distance', 'Atomic Mixing', 'Compound', 'Entry', 'Formula', 'Element 1', 'Element 1 Composition', 'Element 1 At. %', 'Element 2', 'Element 2 Composition', 'Element 2 At. %']]

# Save DataFrame as Excel
excel_filename = 'merged_RMX_3.xlsx'
excel_path = os.path.join(desktop_path, excel_filename)

merged_RMX_3.to_excel(excel_path, index=False)

print(f"Data has been saved to '{excel_path}'")
merged_RMX_3

Data has been saved to '/Users/emiljaffal/Desktop/merged_RMX_3.xlsx'

,Distance,Atomic Mixing,Compound,Entry,Formula,Element 1,Element 1 Composition,Element 1 At. %,Element 2,Element 2 Composition,Element 2 At. %
0,2.032,full_occupancy,Ni-Ge,1008282,Ge3LuNi5,Ni,5,62.50,Ge,3,37.50
1,2.033,full_occupancy,Ni-Ge,1718687,Ge3Ni5Yb,Ni,5,62.50,Ge,3,37.50
2,2.034,full_occupancy,Ni-Ge,1402064,ErGe3Ni5,Ni,5,62.50,Ge,3,37.50
3,2.036,full_occupancy,Ni-Ge,1718681,Ge3Ni5Yb,Ni,5,62.50,Ge,3,37.50
4,2.036,full_occupancy,Ni-Ge,1818130,Ge3Ni5Tm,Ni,5,62.50,Ge,3,37.50
...,...,...,...,...,...,...,...,...,...,...,...
16298,2.926,full_occupancy,Lu-Os,300201,Ge6Lu4Os7,Lu,4,36.36,Os,7,63.64
16299,2.661,full_occupancy,Os-Sn,460299,Os4Sn13Th3,Os,4,23.53,Sn,13,76.47
16300,3.377,full_occupancy,U-Sn,461045,Rh4Sn13U3,U,3,18.75,Sn,13,81.25
16301,2.935,full_occupancy,U-Os,538375,Ge6Os7U4,U,4,36.36,Os,7,63.64
16302,2.880,full_occupancy,Sc-Os,538820,Ge6Os7Sc4,Sc,4,36.36,Os,7,63.64

In [346]:
merged_RMX_3.iloc[4292]

Distance                          2.409
Atomic Mixing            full_occupancy
Compound                          Co-Si
Entry                            303155
Formula                     Co1.5Si0.5U
Element 1                            Co
Element 1 Composition                15
Element 1 At. %                    75.0
Element 2                            Si
Element 2 Composition                 5
Element 2 At. %                    25.0
Name: 4292, dtype: object

In [347]:
import pandas as pd

# Assuming your DataFrame is already loaded and named merged_RMX_3

# Make a copy of the DataFrame
merged_RMX_3_copy = merged_RMX_3.copy()

# Create lists to store the new columns
element_3 = []
element_3_composition = []

# Iterate through each row in the DataFrame
for index, row in merged_RMX_3_copy.iterrows():
    # Get the elements listed in the row
    element_1 = row['Element 1']
    element_2 = row['Element 2']
    
    # Extract the compound formula
    formula = row['Formula']
    
    # Define the pairs of letters in the formula
    formula_pairs = [formula[i:i+2] for i in range(0, len(formula), 2)]
    
    # Find the first pair of letters in the formula that isn't element 1 or the number after, and also isn't element 2 or the number after
    for i in range(len(formula_pairs)):
        pair = formula_pairs[i]
        if pair != element_1 and pair != element_2:
            # Check if the pair contains only letters
            if pair.isalpha():
                element_3_value = pair
                # Set the composition as 1
                element_3_composition_value = 1
            else:
                # If the pair contains numbers as well, take the letters part as element 3
                element_3_value = ''.join(filter(str.isalpha, pair))
                # Set the composition as 1
                element_3_composition_value = 1
            break
    else:
        # If all pairs are element 1 or the number after, and element 2 or the number after, assign element 1 and its composition
        element_3_value = element_1
        element_3_composition_value = row['Element 1 Composition']
    
    # Append the values to the lists
    element_3.append(element_3_value)
    element_3_composition.append(element_3_composition_value)

# Add the new columns to the DataFrame
merged_RMX_3_copy['Element 3'] = element_3
merged_RMX_3_copy['Element 3 Composition'] = element_3_composition

merged_RMX_3_copy

,Distance,Atomic Mixing,Compound,Entry,Formula,Element 1,Element 1 Composition,Element 1 At. %,Element 2,Element 2 Composition,Element 2 At. %,Element 3,Element 3 Composition
0,2.032,full_occupancy,Ni-Ge,1008282,Ge3LuNi5,Ni,5,62.50,Ge,3,37.50,L,1
1,2.033,full_occupancy,Ni-Ge,1718687,Ge3Ni5Yb,Ni,5,62.50,Ge,3,37.50,N,1
2,2.034,full_occupancy,Ni-Ge,1402064,ErGe3Ni5,Ni,5,62.50,Ge,3,37.50,Er,1
3,2.036,full_occupancy,Ni-Ge,1718681,Ge3Ni5Yb,Ni,5,62.50,Ge,3,37.50,N,1
4,2.036,full_occupancy,Ni-Ge,1818130,Ge3Ni5Tm,Ni,5,62.50,Ge,3,37.50,N,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...
16298,2.926,full_occupancy,Lu-Os,300201,Ge6Lu4Os7,Lu,4,36.36,Os,7,63.64,Ge,1
16299,2.661,full_occupancy,Os-Sn,460299,Os4Sn13Th3,Os,4,23.53,Sn,13,76.47,S,1
16300,3.377,full_occupancy,U-Sn,461045,Rh4Sn13U3,U,3,18.75,Sn,13,81.25,Rh,1
16301,2.935,full_occupancy,U-Os,538375,Ge6Os7U4,U,4,36.36,Os,7,63.64,Ge,1
16302,2.880,full_occupancy,Sc-Os,538820,Ge6Os7Sc4,Sc,4,36.36,Os,7,63.64,Ge,1

In [348]:
merged_RMX_3_copy2 = merged_RMX_3.copy()

In [349]:
import pandas as pd
import re
import os

# Assuming merged_RMX_3_copy2 is your DataFrame

# Function to find the third element and its composition from the formula
def find_element_3_and_composition(formula, element_1, element_2):
    # Remove Element 1 and Element 2 from the formula
    remaining_formula = formula.replace(element_1, '').replace(element_2, '')
    
    # Remove numbers from the remaining formula
    remaining_formula = ''.join([char for char in remaining_formula if not char.isdigit()])
    
    # Split the remaining string by "-" and remove any empty strings
    remaining_elements = [elem.strip() for elem in remaining_formula.split("-") if elem.strip()]
    
    # Assuming there will be only one remaining element
    if len(remaining_elements) == 1:
        element_3 = remaining_elements[0]
        
        # Extracting the composition of Element 3
        composition_match = re.search(rf"{element_3}(\d+)", formula)
        if composition_match:
            composition = composition_match.group(1)
        else:
            # If no number found after Element 3, set composition to 1
            composition = '1'
        
        return element_3, composition
    else:
        return None, None

# Apply the function to create Element 3 and Element 3 Composition columns
merged_RMX_3_copy2[['Element 3', 'Element 3 Composition']] = merged_RMX_3_copy2.apply(lambda row: pd.Series(find_element_3_and_composition(row['Formula'], row['Element 1'], row['Element 2'])), axis=1)

In [350]:
merged_RMX_3_copy2

,Distance,Atomic Mixing,Compound,Entry,Formula,Element 1,Element 1 Composition,Element 1 At. %,Element 2,Element 2 Composition,Element 2 At. %,Element 3,Element 3 Composition
0,2.032,full_occupancy,Ni-Ge,1008282,Ge3LuNi5,Ni,5,62.50,Ge,3,37.50,Lu,1
1,2.033,full_occupancy,Ni-Ge,1718687,Ge3Ni5Yb,Ni,5,62.50,Ge,3,37.50,Yb,1
2,2.034,full_occupancy,Ni-Ge,1402064,ErGe3Ni5,Ni,5,62.50,Ge,3,37.50,Er,1
3,2.036,full_occupancy,Ni-Ge,1718681,Ge3Ni5Yb,Ni,5,62.50,Ge,3,37.50,Yb,1
4,2.036,full_occupancy,Ni-Ge,1818130,Ge3Ni5Tm,Ni,5,62.50,Ge,3,37.50,Tm,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...
16298,2.926,full_occupancy,Lu-Os,300201,Ge6Lu4Os7,Lu,4,36.36,Os,7,63.64,Ge,6
16299,2.661,full_occupancy,Os-Sn,460299,Os4Sn13Th3,Os,4,23.53,Sn,13,76.47,Th,3
16300,3.377,full_occupancy,U-Sn,461045,Rh4Sn13U3,U,3,18.75,Sn,13,81.25,Rh,4
16301,2.935,full_occupancy,U-Os,538375,Ge6Os7U4,U,4,36.36,Os,7,63.64,Ge,6
16302,2.880,full_occupancy,Sc-Os,538820,Ge6Os7Sc4,Sc,4,36.36,Os,7,63.64,Ge,6

In [351]:
merged_RMX_3_copy2.iloc[5482]

Distance                          2.865
Atomic Mixing            full_occupancy
Compound                          Tm-Ni
Entry                           1716193
Formula                  In20Ni9.00Tm10
Element 1                            Tm
Element 1 Composition                10
Element 1 At. %                     1.1
Element 2                            Ni
Element 2 Composition               900
Element 2 At. %                    98.9
Element 3                           In.
Element 3 Composition                 0
Name: 5482, dtype: object

In [352]:
merged_RMX_3_copy2.iloc[4292]

Distance                          2.409
Atomic Mixing            full_occupancy
Compound                          Co-Si
Entry                            303155
Formula                     Co1.5Si0.5U
Element 1                            Co
Element 1 Composition                15
Element 1 At. %                    75.0
Element 2                            Si
Element 2 Composition                 5
Element 2 At. %                    25.0
Element 3                           ..U
Element 3 Composition                 1
Name: 4292, dtype: object

In [353]:
import pandas as pd
import os

# Read the data into DataFrame merged_RMX_3_copy2

# Remove '.' in 'Element 1', 'Element 2', and 'Element 3'
merged_RMX_3_copy2['Element 1'] = merged_RMX_3_copy2['Element 1'].astype(str).str.replace('.', '')
merged_RMX_3_copy2['Element 2'] = merged_RMX_3_copy2['Element 2'].astype(str).str.replace('.', '')
merged_RMX_3_copy2['Element 3'] = merged_RMX_3_copy2['Element 3'].astype(str).str.replace('.', '')

# Convert 'Element 1 Composition', 'Element 2 Composition', and 'Element 3 Composition' to numeric
merged_RMX_3_copy2[['Element 1 Composition', 'Element 2 Composition', 'Element 3 Composition']] = merged_RMX_3_copy2[['Element 1 Composition', 'Element 2 Composition', 'Element 3 Composition']].apply(pd.to_numeric, errors='coerce')

# Calculate the sum of each row in 'Element 1 Composition', 'Element 2 Composition', and 'Element 3 Composition'
merged_RMX_3_copy2['sum_compositions'] = merged_RMX_3_copy2[['Element 1 Composition', 'Element 2 Composition', 'Element 3 Composition']].sum(axis=1)

# Calculate Element 1 At. %, Element 2 At. %, and Element 3 At. %
merged_RMX_3_copy2['Element 1 At. %'] = (merged_RMX_3_copy2['Element 1 Composition'] / merged_RMX_3_copy2['sum_compositions']) * 100
merged_RMX_3_copy2['Element 2 At. %'] = (merged_RMX_3_copy2['Element 2 Composition'] / merged_RMX_3_copy2['sum_compositions']) * 100
merged_RMX_3_copy2['Element 3 At. %'] = (merged_RMX_3_copy2['Element 3 Composition'] / merged_RMX_3_copy2['sum_compositions']) * 100

# Drop the temporary column 'sum_compositions'
merged_RMX_3_copy2.drop(columns=['sum_compositions'], inplace=True)

# Round the percentages to 2 decimal points
merged_RMX_3_copy2 = merged_RMX_3_copy2.round({'Element 1 At. %': 2, 'Element 2 At. %': 2, 'Element 3 At. %': 2})


# Define the file path to save the DataFrame
file_path = os.path.join(os.path.expanduser("~"), "Desktop", "Final_ternary.xlsx")

# Save the DataFrame to an Excel file
merged_RMX_3_copy2.to_excel(file_path, index=False)

print(f"DataFrame saved to {file_path}")

merged_RMX_3_copy2

DataFrame saved to /Users/emiljaffal/Desktop/Final_ternary.xlsx

,Distance,Atomic Mixing,Compound,Entry,Formula,Element 1,Element 1 Composition,Element 1 At. %,Element 2,Element 2 Composition,Element 2 At. %,Element 3,Element 3 Composition,Element 3 At. %
0,2.032,full_occupancy,Ni-Ge,1008282,Ge3LuNi5,Ni,5,55.56,Ge,3,33.33,Lu,1,11.11
1,2.033,full_occupancy,Ni-Ge,1718687,Ge3Ni5Yb,Ni,5,55.56,Ge,3,33.33,Yb,1,11.11
2,2.034,full_occupancy,Ni-Ge,1402064,ErGe3Ni5,Ni,5,55.56,Ge,3,33.33,Er,1,11.11
3,2.036,full_occupancy,Ni-Ge,1718681,Ge3Ni5Yb,Ni,5,55.56,Ge,3,33.33,Yb,1,11.11
4,2.036,full_occupancy,Ni-Ge,1818130,Ge3Ni5Tm,Ni,5,55.56,Ge,3,33.33,Tm,1,11.11
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16298,2.926,full_occupancy,Lu-Os,300201,Ge6Lu4Os7,Lu,4,23.53,Os,7,41.18,Ge,6,35.29
16299,2.661,full_occupancy,Os-Sn,460299,Os4Sn13Th3,Os,4,20.00,Sn,13,65.00,Th,3,15.00
16300,3.377,full_occupancy,U-Sn,461045,Rh4Sn13U3,U,3,15.00,Sn,13,65.00,Rh,4,20.00
16301,2.935,full_occupancy,U-Os,538375,Ge6Os7U4,U,4,23.53,Os,7,41.18,Ge,6,35.29
16302,2.880,full_occupancy,Sc-Os,538820,Ge6Os7Sc4,Sc,4,23.53,Os,7,41.18,Ge,6,35.29

In [354]:
# Find instances of '.' in the DataFrame
entries_with_decimal = merged_RMX_3_copy2[merged_RMX_3_copy2['Formula'].str.contains('\.')]

# Display the entries where the decimal is found
print(entries_with_decimal)

       Distance   Atomic Mixing Compound    Entry         Formula Element 1  \
689       2.921  full_occupancy    La-Ni  1232797    LaNi4.8Sn0.2        La
806       2.633  full_occupancy    Ni-In  1716193  In20Ni9.00Tm10        Ni
1723      2.156  full_occupancy    Ni-Si  1963540     Ho3.Ni12Si4        Ni
4292      2.409  full_occupancy    Co-Si   303155     Co1.5Si0.5U        Co
4842      2.791  full_occupancy     U-Co   303155     Co1.5Si0.5U         U
4989      2.725  full_occupancy    Ho-Ni  1963540     Ho3.Ni12Si4        Ho
5482      2.865  full_occupancy    Tm-Ni  1716193  In20Ni9.00Tm10        Tm
6732      3.117  full_occupancy    Sm-Ga  1935820    Ga8.0Pd3.0Sm        Sm
6924      2.566  full_occupancy    Fe-Ga  1840102     Fe1.4Ga0.6U        Fe
8199      3.032  full_occupancy    Pr-Ge   552077    Fe0.85Ge7Pr4        Pr
9294      2.780  full_occupancy    Sc-Co  1005492  Co0.25ScSi1.75        Sc
9823      2.639  full_occupancy    Rh-Sn   460318    Gd3.3Rh4Sn13        Rh
10739     2.572  full_occupancy    Pd-Ga  1935820    Ga8.0Pd3.0Sm        Pd
10878     2.262  full_occupancy    Fe-Ge   552077    Fe0.85Ge7Pr4        Fe
13711     3.384  full_occupancy    Gd-Sn   460318    Gd3.3Rh4Sn13        Gd

       Element 1 Composition  Element 1 At. % Element 2  \
689                        1             2.00        Ni
806                      900            96.77        In
1723                      12            70.59        Si
4292                      15            71.43        Si
4842                       1             5.88        Co
4989                       3            15.79        Ni
5482                      10             1.10        Ni
6732                       1             1.22        Ga
6924                      14            66.67        Ga
8199                       4            33.33        Ge
9294                       1             3.70        Co
9823                       4            22.22        Sn
10739                     30            27.03        Ga
10878                     85            88.54        Ge
13711                     33            66.00        Sn

       Element 2 Composition  Element 2 At. % Element 3  \
689                       48            96.00        Sn
806                       20             2.15        Tm
1723                       4            23.53        Ho
4292                       5            23.81         U
4842                      15            88.24        Si
4989                      12            63.16        Si
5482                     900            98.90        In
6732                      80            97.56        Pd
6924                       6            28.57         U
8199                       7            58.33        Fe
9294                      25            92.59        Si
9823                      13            72.22        Gd
10739                     80            72.07        Sm
10878                      7             7.29        Pr
13711                     13            26.00        Rh

       Element 3 Composition  Element 3 At. %
689                        1             2.00
806                       10             1.08
1723                       1             5.88
4292                       1             4.76
4842                       1             5.88
4989                       4            21.05
5482                       0             0.00
6732                       1             1.22
6924                       1             4.76
8199                       1             8.33
9294                       1             3.70
9823                       1             5.56
10739                      1             0.90
10878                      4             4.17
13711                      4             8.00