In [14]:
import pandas as pd
import os

desktop_path = os.path.join(os.path.expanduser('~'), 'Desktop')
sheet_filename = 'M-X_CIFs_full_occupancy_sorted_tags_element_pairs.xlsx'
sheet_path = os.path.join(desktop_path, sheet_filename)

df = pd.read_excel(sheet_path)
df

           File  Distance   Atomic Mixing
0   1250691.cif     2.386  full_occupancy
1    554689.cif     2.444  full_occupancy
2   1837984.cif     2.450  full_occupancy
3   1819720.cif     2.450  full_occupancy
4   1002170.cif     2.452  full_occupancy
5   1142335.cif     2.453  full_occupancy
6   1200981.cif     2.503  full_occupancy
7   1834527.cif     2.518  full_occupancy
8    528976.cif     2.518  full_occupancy
9   1142340.cif     2.523  full_occupancy
10  1128955.cif     2.534  full_occupancy
11  1250819.cif     2.535  full_occupancy
12  1837981.cif     2.535  full_occupancy
13  1607854.cif     2.537  full_occupancy
14  1819723.cif     2.539  full_occupancy
15  1930244.cif     2.542  full_occupancy
16  1054742.cif     2.546  full_occupancy
17  1128956.cif     2.560  full_occupancy
18  1731676.cif     2.595  full_occupancy
19  1717936.cif     2.608  full_occupancy
20  1407717.cif     2.613  full_occupancy
21   311764.cif     2.613  full_occupancy
22   547242.cif     2.615  full_occupancy
23  1928924.cif     2.615  full_occupancy
24   532943.cif     2.617  full_occupancy
25   532172.cif     2.617  full_occupancy
26  1819719.cif     2.617  full_occupancy
27  1837982.cif     2.617  full_occupancy
28  1831363.cif     2.617  full_occupancy
29  1930248.cif     2.618  full_occupancy
30  1959677.cif     2.618  full_occupancy
31  1301772.cif     2.619  full_occupancy
32   453919.cif     2.621  full_occupancy
33   453316.cif     2.625  full_occupancy
34  1142339.cif     2.647  full_occupancy

In [8]:
xl = pd.ExcelFile(sheet)

xl.sheet_names  # see all sheet names

['Ni-Sn',
 'Ni-Ni',
 'Ni-Si',
 'Co-Si',
 'Ir-Sb',
 'Fe-Fe',
 'Fe-Sn',
 'Fe-Sb',
 'Ni-Sb',
 'Fe-Si',
 'Co-Sb',
 'Ni-In',
 'Fe-Ge',
 'Pt-Sn',
 'Pt-Pt',
 'Co-Ge',
 'Ge-Ge',
 'Co-Co',
 'Ru-Sb',
 'Ru-Sn',
 'Pd-Sb',
 'Ru-In',
 'Ir-In',
 'Ir-Si',
 'Pd-Sn',
 'Rh-Sn',
 'Rh-Rh',
 'Sn-Sn',
 'Pd-Pd',
 'Pd-In',
 'Pd-Ga',
 'Ir-Ga',
 'Sb-Sb',
 'Ru-Ge',
 'Rh-Ga',
 'Co-Sn',
 'Pd-Ge',
 'Pt-Si',
 'Pt-Ge',
 'Pd-Si',
 'Fe-Ga',
 'Ir-Sn',
 'Co-In',
 'Pt-In',
 'Ni-Ge',
 'Rh-Si',
 'Pt-Ga',
 'Ga-Ga',
 'Rh-Sb',
 'Ir-Ge',
 'Ru-Ga',
 'Pt-Sb',
 'Ni-Ga',
 'Rh-Ge',
 'Ru-Si',
 'Os-Ge',
 'Si-Si',
 'Os-Sn',
 'Rh-In',
 'Co-Ga',
 'Os-Sb',
 'Os-Si',
 'Os-Ga',
 'In-In',
 'Ru-Ru']

In [16]:
len(xl.sheet_names)

65

In [31]:
import pandas as pd
import os

desktop_path = os.path.join(os.path.expanduser('~'), 'Desktop')
sheet_filename = 'M-X_CIFs_full_occupancy_sorted_tags_element_pairs.xlsx'
sheet_path = os.path.join(desktop_path, sheet_filename)

# Read the Excel file
xl = pd.ExcelFile(sheet_path)

# Initialize an empty list to store DataFrames for each sheet
dfs = []

# Iterate over each sheet, read data, and append sheet name as a new column
for sheet_name in xl.sheet_names:
    df = xl.parse(sheet_name)  # Read data from the current sheet
    df['Compound'] = sheet_name  # Add a new column with sheet name
    dfs.append(df)  # Append the modified DataFrame to the list

# Concatenate all DataFrames into a single DataFrame
result_df = pd.concat(dfs, ignore_index=True)

# Filtering the DataFrame
# Define lists of M and X elements
M_elements = ['Fe', 'Co', 'Ni', 'Ru', 'Rh', 'Pd', 'Os', 'Ir', 'Pt']
X_elements = ['Si', 'Ga', 'Ge', 'In', 'Sn', 'Sb']

# Filter the DataFrame based on M and X elements
filtered_df = result_df[result_df['Compound'].apply(lambda x: any(m in x for m in M_elements)) & 
                        result_df['Compound'].apply(lambda x: any(x.endswith('-' + x_elem) for x_elem in X_elements))]

# Selecting desired columns
desired_columns = ['File', 'Distance', 'Atomic Mixing', 'Compound']
filtered_df = filtered_df[desired_columns]
filtered_df

             File  Distance   Atomic Mixing Compound
0     1250691.cif     2.386  full_occupancy    Ni-Sn
1      554689.cif     2.444  full_occupancy    Ni-Sn
2     1837984.cif     2.450  full_occupancy    Ni-Sn
3     1819720.cif     2.450  full_occupancy    Ni-Sn
4     1002170.cif     2.452  full_occupancy    Ni-Sn
...           ...       ...             ...      ...
1663   555792.cif     2.426  full_occupancy    Os-Si
1664   452823.cif     2.439  full_occupancy    Os-Si
1665   456001.cif     2.457  full_occupancy    Os-Si
1666   261309.cif     2.481  full_occupancy    Os-Ga
1667   526972.cif     2.481  full_occupancy    Os-Ga

[1285 rows x 4 columns]

In [32]:
# Selecting desired columns
desired_columns = ['File', 'Distance', 'Atomic Mixing', 'Compound']
filtered_df = filtered_df[desired_columns]

# Group by M and X elements and calculate average and standard deviation of Distance
grouped_df = filtered_df.groupby('Compound').agg({'Distance': ['mean', 'std']})

# Flatten MultiIndex columns
grouped_df.columns = ['_'.join(col).strip() for col in grouped_df.columns.values]

# Reset index
grouped_df.reset_index(inplace=True)

# Save grouped_df as Excel
excel_filename = 'MX_grouped_data.xlsx'
excel_path = os.path.join(desktop_path, excel_filename)

grouped_df.to_excel(excel_path, index=False)

print(f"Data has been saved to '{excel_path}'")

Data has been saved to '/Users/emiljaffal/Desktop/MX_grouped_data.xlsx'

In [39]:
import pandas as pd
import os

desktop_path = os.path.join(os.path.expanduser('~'), 'Desktop')
sheet_filename = 'R-X_CIFs_full_occupancy_sorted_tags_element_pairs.xlsx'
sheet_path = os.path.join(desktop_path, sheet_filename)

# Read the Excel file
xl = pd.ExcelFile(sheet_path)

# Initialize an empty list to store DataFrames for each sheet
dfs = []

# Iterate over each sheet, read data, and append sheet name as a new column
for sheet_name in xl.sheet_names:
    df = xl.parse(sheet_name)  # Read data from the current sheet
    df['Compound'] = sheet_name  # Add a new column with sheet name
    dfs.append(df)  # Append the modified DataFrame to the list

# Concatenate all DataFrames into a single DataFrame
result_df = pd.concat(dfs, ignore_index=True)

# Filtering the DataFrame
# Define lists of M and X elements
R_elements = ['Sc', 'Y', 'La', 'Ce', 'Pr', 'Nd', 'Sm', 'Eu', 'Gd', 'Tb', 'Dy', 'Ho', 'Er', 'Tm', 'Yb', 'Lu', 'Th', 'U']
X_elements = ['Si', 'Ga', 'Ge', 'In', 'Sn', 'Sb']

# Filter the DataFrame based on M and X elements
filtered_df = result_df[result_df['Compound'].apply(lambda x: any(r in x for r in R_elements)) & 
                        result_df['Compound'].apply(lambda x: any(x.endswith('-' + x_elem) for x_elem in X_elements))]

# Selecting desired columns
desired_columns = ['File', 'Distance', 'Atomic Mixing', 'Compound']
filtered_df = filtered_df[desired_columns]
filtered_df

             File  Distance   Atomic Mixing Compound
467    525300.cif     2.888  full_occupancy    Eu-Si
468   1810191.cif     3.079  full_occupancy    Eu-Si
469   2040771.cif     3.105  full_occupancy    Eu-Si
470   1810725.cif     3.110  full_occupancy    Eu-Si
471    455984.cif     3.126  full_occupancy    Eu-Si
...           ...       ...             ...      ...
4891   453382.cif     3.159  full_occupancy    Th-Sb
4892   531000.cif     3.159  full_occupancy    Th-Sb
4893   451240.cif     3.182  full_occupancy    Th-Sb
4894   451241.cif     3.240  full_occupancy    Th-Sb
4895   534387.cif     3.248  full_occupancy    Th-Sb

[2897 rows x 4 columns]

In [40]:
# Selecting desired columns
desired_columns = ['File', 'Distance', 'Atomic Mixing', 'Compound']
filtered_df = filtered_df[desired_columns]

# Group by M and X elements and calculate average and standard deviation of Distance
grouped_df = filtered_df.groupby('Compound').agg({'Distance': ['mean', 'std']})

# Flatten MultiIndex columns
grouped_df.columns = ['_'.join(col).strip() for col in grouped_df.columns.values]

# Reset index
grouped_df.reset_index(inplace=True)

# Save grouped_df as Excel
excel_filename = 'RX_grouped_data.xlsx'
excel_path = os.path.join(desktop_path, excel_filename)

grouped_df.to_excel(excel_path, index=False)

print(f"Data has been saved to '{excel_path}'")

Data has been saved to '/Users/emiljaffal/Desktop/RX_grouped_data.xlsx'

In [37]:
import pandas as pd
import os

desktop_path = os.path.join(os.path.expanduser('~'), 'Desktop')
sheet_filename = 'R-M_CIFs_full_occupancy_sorted_tags_element_pairs.xlsx'
sheet_path = os.path.join(desktop_path, sheet_filename)

# Read the Excel file
xl = pd.ExcelFile(sheet_path)

# Initialize an empty list to store DataFrames for each sheet
dfs = []

# Iterate over each sheet, read data, and append sheet name as a new column
for sheet_name in xl.sheet_names:
    df = xl.parse(sheet_name)  # Read data from the current sheet
    df['Compound'] = sheet_name  # Add a new column with sheet name
    dfs.append(df)  # Append the modified DataFrame to the list

# Concatenate all DataFrames into a single DataFrame
result_df = pd.concat(dfs, ignore_index=True)

# Filtering the DataFrame
# Define lists of M and X elements
R_elements = ['Sc', 'Y', 'La', 'Ce', 'Pr', 'Nd', 'Sm', 'Eu', 'Gd', 'Tb', 'Dy', 'Ho', 'Er', 'Tm', 'Yb', 'Lu', 'Th', 'U']
M_elements = ['Fe', 'Co', 'Ni', 'Ru', 'Rh', 'Pd', 'Os', 'Ir', 'Pt']

# Filter the DataFrame based on M and X elements
filtered_df = result_df[result_df['Compound'].apply(lambda x: any(r in x for r in R_elements)) & 
                        result_df['Compound'].apply(lambda x: any(x.endswith('-' + m_elem) for m_elem in M_elements))]

# Selecting desired columns
desired_columns = ['File', 'Distance', 'Atomic Mixing', 'Compound']
filtered_df = filtered_df[desired_columns]
filtered_df

             File  Distance   Atomic Mixing Compound
902   1643161.cif     2.707  full_occupancy    Nd-Fe
903    260460.cif     2.856  full_occupancy    Nd-Fe
904   1430804.cif     2.909  full_occupancy    Nd-Fe
905   1721845.cif     2.968  full_occupancy    Nd-Fe
906    554633.cif     2.968  full_occupancy    Nd-Fe
...           ...       ...             ...      ...
8280   458147.cif     2.899  full_occupancy    Yb-Rh
8281   458151.cif     3.081  full_occupancy    Yb-Rh
8282   526157.cif     3.081  full_occupancy    Yb-Rh
8283   526180.cif     3.076  full_occupancy    Yb-Os
8284   458157.cif     3.090  full_occupancy    Yb-Os

[4441 rows x 4 columns]

In [38]:
# Selecting desired columns
desired_columns = ['File', 'Distance', 'Atomic Mixing', 'Compound']
filtered_df = filtered_df[desired_columns]

# Group by M and X elements and calculate average and standard deviation of Distance
grouped_df = filtered_df.groupby('Compound').agg({'Distance': ['mean', 'std']})

# Flatten MultiIndex columns
grouped_df.columns = ['_'.join(col).strip() for col in grouped_df.columns.values]

# Reset index
grouped_df.reset_index(inplace=True)

# Save grouped_df as Excel
excel_filename = 'RM_grouped_data.xlsx'
excel_path = os.path.join(desktop_path, excel_filename)

grouped_df.to_excel(excel_path, index=False)

print(f"Data has been saved to '{excel_path}'")

Data has been saved to '/Users/emiljaffal/Desktop/RM_grouped_data.xlsx'